server:
  port: 8085

spring:
  application:
    name: say-hello

eureka:
  client:
    #eureka 서버 등록 가능
    register-with-eureka: true
    #외부에서 검색 가능한 형태
    fetch-registry: true
    #eureka 서버 위치 폴더 지정
    service-url:
      #eureka 라는 엔드포인트에 현재 마이크로서비스 등록
      defaultZone: http://localhost:8761/eureka